### ISSUE TITLE
Little glitch in the intro section

### ISSUE THREAD

**Issue by Bokelmann** [getgrav/grav-skeleton-landio-site#2]
I guess that gap under the mockup is unwanted.
![intro](https://cloud.githubusercontent.com/assets/11684846/11762554/f88999bc-a0ea-11e5-92e0-f76978bd5c6a.png)

**Comment by Bokelmann** [comment]
Doh! Just noticed this was reported already. If it's fixed already demo should be updated ;-)

**Comment by hexplor** [comment]
Fixed :) thanks for reminder :) http://demo.getgrav.org/landio-skeleton/
