### ISSUE TITLE
Login nav item string

### ISSUE THREAD

**Issue by sheldonkotyk** [getgrav/grav-skeleton-landio-site#3]
<img width="340" alt="screen shot 2016-01-16 at 18 44 55" src="https://cloud.githubusercontent.com/assets/622598/12375652/5a30df02-bc81-11e5-8ff8-d0e89292e543.png">

**Comment by hexplor** [comment]
Fixed, user/config/login.yaml was set to "enabled" even if there's no Login plugin installed. This shouldn't display anymore. Thanks :)
