### ISSUE TITLE
Error Message on DEMO Page

### ISSUE THREAD

**Issue by feldmarv** [getgrav/grav-skeleton-landio-site#4]
There is an error message on the demo page:
http://demo.getgrav.org/landio-skeleton/

![bildschirmfoto 2016-05-09 um 22 11 20](https://cloud.githubusercontent.com/assets/9105618/15126603/01dabe0c-1633-11e6-8654-7b8a8cd90a34.png)

**Comment by rhukster** [comment]
Fixed, had an out of date admin plugin there.

**Comment by feldmarv** [comment]
great!
