### ISSUE TITLE
Testimonial wrong linked

### ISSUE THREAD

**Issue by feldmarv** [getgrav/grav-skeleton-landio-site#5]
Testimoninal carousel-indicators are not linked to the correct testimonial entry.

**Comment by feldmarv** [comment]
Any idea why this is wrong linked?

![bildschirmfoto 2016-05-10 um 10 44 35](https://cloud.githubusercontent.com/assets/9105618/15140628/4e5d3214-169c-11e6-8e76-4cc46ee5eea8.png)

**Comment by rhukster** [comment]
Seems they were being randomized - https://github.com/getgrav/grav-theme-landio/commit/20be63352d00b5ed8354b5a031c81845c6d780a8

Fixed in develop
